export const data = [
  { "id":1,
    "productName": "Material1",
    "uom": "Discard",
    "date":"10/02/2023",
    "dims": "Stores",
    "internalPartNo": "INPN123",
    "description": "Damage Reason","description1": "",
    "shotWeight":"kgs",
    "status":"Received",
    "Items":"mat1,mat2,mat3,mat4",
    "Qty":"4143",
    "RQty":"400",
  },
  {
    "id": 2,
    "productName": "Material2",
    "uom": "Discard",
    "dims": "Quality",
    "internalPartNo": "EPN123",
    "description": "Damage Reason","description1": "Need to Take Care",
    "shotWeight":"kgs",
    "date":"10/02/2023",
    "status":"Approved",
    "Items":"materail1,materail13,materail3",
    "Qty":"14343",
    "RQty":"11",
 
  },
  {
    "id": 3,
    "productName": "Material3",
    "uom": "Scrap",
    "dims": "Production",
    "internalPartNo": "RTH123",
    "description": "Damage Reason","description1": "",
    "shotWeight":"Count",
    "date":"10/02/2023",
    "status":"Received",
    "Items":"materail1,materail13,materail3",
    "Qty":"234",
    "RQty":"21",
 
  },
  {
    "id": 4,
    "productName": "Material4",
    "uom": "Scrap",
    "dims": "Administration",
    "internalPartNo": "ERT123",
    "description": "Damage Reason","description1": "",
    "shotWeight":"Count",
    "date":"10/02/2023",
    "status":"Received",
    "Items":"materail1,materail13,materail3",
    "Qty":"342",
    "RQty":"31",
 
  },
  {
    "id": 5,
    "productName": "Material5",
    "uom": "Service",
    "dims": "Production",
    "internalPartNo": "DFTR123",
    "description": "Damage Reason","description1": "Need to Take Care",
    "shotWeight":"Count",
    "date":"10/02/2023",
    "status":"Approved",
    "Items":"materail1,materail13,materail3",
    "Qty":"4543",
    "RQty":"89",
 
  }
]