export const data = [
    { "id":1,
    "Date":"30/01/2023",
      "productName": "PO2321332",
      "cusName": "Vinayaga Welders",
      "part": "VJP Foundaries",
      "quantity": "98",
      "cost": "43567",
      "orderStatus":"Awaiting_Approval",
    },
    {
      "id": 2,
      "Date":"22/01/2023",
      "productName": "PO23323243",
      "cusName": "Material Suppliers Pvt Ltd",
      "part": "VJP Foundaries",
      "quantity" :"121",
      "cost": "56789",
      "orderStatus":"Approved",
    },
    {
      "id": 3,
      "Date":"18/01/2023",
      "productName": "PO2367676",
      "cusName": "Balaji Industries",
      "part": "VJP Foundaries",
      "quantity": "486",
      "cost": "45678",
      "orderStatus":"In-Production",
    },
    {
      "id": 4,
      "Date":"14/01/2023",
      "productName": "PO2677654",
      "cusName": "Noor Painting",
      "part": "VJP Foundaries",
      "quantity": "88",
      "cost": "88898",
      "orderStatus":"Partially-Dispatched",
    },
    {
      "id": 5,
      "Date":"12/01/2023",
      "productName": "PO2379898",
      "cusName": "Gold Zone Painting",
      "part": "VJP Foundaries",
      "quantity": "12",
      "cost": "12345",
      "orderStatus":"Closed",
    }
  ]