export const data = [
    { "id":1,
    "Date":"30/01/2023",
      "productName": "PO2321332",
      "cusName": "Vinayaga Welders",
      "part": "VJP Foundaries",
      "quantity": "98",
      "cost": "43567",
      "orderStatus":"Awaiting_Approval",
       "unitprice":"1",
       "amount":"98",
       "gstAmount":"15",
       "gstperc":"12%"
    },
    {
      "id": 2,
      "Date":"22/01/2023",
      "productName": "PO23323243",
      "cusName": "Material Suppliers Pvt Ltd",
      "part": "VJP Foundaries",
      "quantity" :"121",
      "cost": "56789",
      "orderStatus":"Approved",
      "unitprice":"2",
       "amount":"242",
       "gstAmount":"32",
       "gstperc":"12%"
    },
    {
      "id": 3,
      "Date":"18/01/2023",
      "productName": "PO2367676",
      "cusName": "Balaji Industries",
      "part": "VJP Foundaries",
      "quantity": "486",
      "cost": "45678",
      "orderStatus":"In-Production",
      "unitprice":".5",
       "amount":"243",
       "gstAmount":"32",
       "gstperc":"12%"
    },
    {
      "id": 4,
      "Date":"14/01/2023",
      "productName": "PO2677654",
      "cusName": "Noor Painting",
      "part": "VJP Foundaries",
      "quantity": "88",
      "cost": "88898",
      "orderStatus":"Partially-Dispatched",
      "unitprice":"3",
       "amount":"272",
       "gstAmount":"33",
       "gstperc":"12%"
    },
    {
      "id": 5,
      "Date":"12/01/2023",
      "productName": "PO2379898",
      "cusName": "Gold Zone Painting",
      "part": "VJP Foundaries",
      "quantity": "12",
      "cost": "12345",
      "orderStatus":"Closed",
      "unitprice":"4",
       "amount":"48",
       "gstAmount":"8",
       "gstperc":"12%"
    }
  ]