export const processData = [
    { "id":1,
      "Process":"Casting",
      "Inward": "",
      "OnWork":"14",
      "OutWard":"34",
    },
    {
        "id":2,
        "Process":"Cutting & Fettling",
        "Inward": "34",
        "OnWork":"12",
        "OutWard":"22",
    },
    {
        "id":3,
        "Process":"Visual Inspection 1",
        "Inward": "22",
        "OnWork":"4",
        "OutWard":"18",
    },
    {
        "id":4,
        "Process":"Heat Treatment",
        "Inward": "18",
        "OnWork":"0",
        "OutWard":"18",
      },
      {
        "id":5,
      "Process":"Shot Blast",
      "Inward": "18",
      "OnWork":"2",
      "OutWard":"16",
      },{
        "id":7,
      "Process":"FPI",
      "Inward": "18",
      "OnWork":"2",
      "OutWard":"16",
      },{
        "id":7,
      "Process":"RTI",
      "Inward": "18",
      "OnWork":"2",
      "OutWard":"16",
      },{
        "id":7,
      "Process":"Visual Inspection 2",
      "Inward": "18",
      "OnWork":"2",
      "OutWard":"16",
      },{
        "id":7,
      "Process":"Machining",
      "Inward": "18",
      "OnWork":"2",
      "OutWard":"16",
      },
  ]