export const data = [
    { "id":1,
      "productName": "R1234567",
      "cusName": "ISRO",
      "part": "Nozzle",
      "quantity": "98",
      "cost": "43567",
      "status":"Awaiting Approval",
    },
    {
      "id": 2,
      "productName": "RQ234567",
      "cusName": "BHEL",
      "part": "Compressor",
      "quantity" :"121",
      "cost": "56789",
      "status":"Approved",
    },
    {
      "id": 3,
      "productName": "R34567QE",
      "cusName": "BHEL",
      "part": "Exhaust",
      "quantity": "486",
      "cost": "45678",
      "status":"In-Production",
    },
    {
      "id": 4,
      "productName": "F34567QE",
      "cusName": "BHEL",
      "part": "Turbine",
      "quantity": "88",
      "cost": "88898",
      "status":"Partially-Dispatched",
    },
    {
      "id": 5,
      "productName": "DF34567QE",
      "cusName": "DRDO",
      "part": "Rotor",
      "quantity": "12",
      "cost": "12345",
      "status":"Closed",
    }
  ]