export const data = [
  { "id":1,
    "productName": "PO Out Sourcing",
    "cusName": "Parellel",
    "dims": "(10,45,16)",
    "internalPartNo": "INPN123",
    "description": "For purpose of out sourcing",
    "shotWeight":"134",
  },
  {
    "id": 2,
    "productName": "Buy Equipments",
    "cusName": "Parellel",
    "dims": "(10,45,16)",
    "internalPartNo": "EPN123",
    "description": "For purpose of buying equips",
    "shotWeight":"122",
  },
  {
    "id": 3,
    "productName": "Materials Inwards",
    "cusName": "Orderly Approval",
    "dims": "(10,45,16)",
    "internalPartNo": "RTH123",
    "description": "For purpose of materials inwards",
    "shotWeight":"100",
  },
  {
    "id": 4,
    "productName": "Materials Transfer",
    "cusName": "Orderly Approval",
    "dims": "(10,45,16)",
    "internalPartNo": "ERT123",
    "description": "For purpose of transfer",
    "shotWeight":"96",
  },
  {
    "id": 5,
    "productName": "Machine Order",
    "cusName": "Orderly Approval",
    "dims": "(10,45,16)",
    "internalPartNo": "DFTR123",
    "description": "Machine Orderr",
    "shotWeight":"59",
  }
]