export const data = [
  { "id":1,
    "productName": "Material1",
    "uom": "Kg",
    "date":"10/02/2023",
    "dims": "Stores",
    "internalPartNo": "INPN123",
    "description": "Description For Request",
    "shotWeight":"Hardware",
    "status":"Accepted",
    "Items":"mat1,mat2,mat3,mat4",
    "Qty":"4143",
    "RQty":"400",
  },
  {
    "id": 2,
    "productName": "Material2",
    "uom": "Liter",
    "dims": "Quality",
    "internalPartNo": "EPN123",
    "description": "Description For Request",
    "shotWeight":"Developement",
    "date":"10/02/2023",
    "status":"Accepted",
    "Items":"materail1,materail13,materail3",
    "Qty":"14343",
    "RQty":"11",
 
  },
  {
    "id": 3,
    "productName": "Material3",
    "uom": "Meter",
    "dims": "Production",
    "internalPartNo": "RTH123",
    "description": "Description For Request",
    "shotWeight":"Testing",
    "date":"10/02/2023",
    "status":"Accepted",
    "Items":"materail1,materail13,materail3",
    "Qty":"234",
    "RQty":"21",
 
  },
  {
    "id": 4,
    "productName": "Material4",
    "uom": "Qty",
    "dims": "Administration",
    "internalPartNo": "ERT123",
    "description": "Description For Request",
    "shotWeight":"Hardware",
    "date":"10/02/2023",
    "status":"Accepted",
    "Items":"materail1,materail13,materail3",
    "Qty":"342",
    "RQty":"31",
 
  },
  {
    "id": 5,
    "productName": "Material5",
    "uom": "Sq-meter",
    "dims": "Production",
    "internalPartNo": "DFTR123",
    "description": "Description For Request",
    "shotWeight":"Testing",
    "date":"10/02/2023",
    "status":"Accepted",
    "Items":"materail1,materail13,materail3",
    "Qty":"4543",
    "RQty":"89",
 
  }
]