export const data = [
  { "id":1,
    "productName": "Praveen",
    "uom": "Kg",
    "date":"10/02/2023",
    "dims": "Stores",
    "internalPartNo": "INPN123",
    "description": "Description For Request",
    "shotWeight":"Hardware",
    "status":"Requested",
    "type":"Service",
    "Item":"Service of shot Blast",
    "Qty":"1",
    "Rdate":"14/02/2023",
  },
  {
    "id": 2,
    "productName": "Dinesh",
    "uom": "Liter",
    "dims": "Quality",
    "internalPartNo": "EPN123",
    "description": "Description For Request",
    "shotWeight":"Developement",
    "date":"10/02/2023",
    "status":"Approved",
    "Item":"mat12",
    "type":"Material",
    "Qty":"6",
    "Rdate":"21/02/2023",
 
  },
  {
    "id": 3,
    "productName": "Kumar",
    "uom": "Meter",
    "dims": "Production",
    "internalPartNo": "RTH123",
    "description": "Description For Request",
    "shotWeight":"Testing",
    "date":"10/02/2023",
    "status":"PO Generated",
    "Item":"Service of Laptop",
    "type":"Service",
    "Qty":"1",
    "Rdate":"26/02/2023",
 
  },
  {
    "id": 4,
    "productName": "Harish",
    "uom": "Qty",
    "dims": "Administration",
    "internalPartNo": "ERT123",
    "description": "Description For Request",
    "shotWeight":"Hardware",
    "date":"10/02/2023",
    "status":"Rejected",
    "Item":"materials41",
    "type":"Material",
    "Qty":"2",
    "Rdate":"31/02/2023",
  },
  {
    "id": 5,
    "productName": "Kalyan",
    "uom": "Sq-meter",
    "dims": "Production",
    "internalPartNo": "DFTR123",
    "description": "Description For Request",
    "shotWeight":"Testing",
    "date":"10/02/2023",
    "status":"Approved",
    "Item":"matert321",
    "type":"Material",
    "Qty":"4",
    "Rdate":"28/02/2023",
 
  }
]