export const data = [
    { "id":1,
      "productName": "Praveen",
      "uom": "Kg",
      "date":"10/02/2023",
      "dims": "Stores",
      "internalPartNo": "mat1",
      "description": "Description For Request",
      "shotWeight":"Hardware",
      "status":"Approved",
      "Items":"mat1,mat2,mat3,mat4",
      "qty":6,"availqty":"54","iqty":6,

    },
    {
      "id": 2,
      "productName": "Dinesh",
      "uom": "Liter",
      "dims": "Quality",
      "internalPartNo": "mat2",
      "description": "Description For Request",
      "shotWeight":"Developement",
      "date":"10/02/2023",
      "status":"Approved",
      "Items":"materail1,materail13,materail3",
      "qty":5,"availqty":"54","iqty":3,
   
    },
    {
      "id": 3,
      "productName": "Kumar",
      "uom": "Meter",
      "dims": "Production",
      "internalPartNo": "mat3",
      "description": "Description For Request",
      "shotWeight":"Testing",
      "date":"10/02/2023",
      "status":"Approved",
      "qty":51,"availqty":"54","iqty":51,
      "Items":"materail1,materail13,materail3"
   
    },
    {
      "id": 4,
      "productName": "Harish",
      "uom": "Qty",
      "dims": "Administration",
      "internalPartNo": "mat4",
      "description": "Description For Request",
      "shotWeight":"Hardware",
      "date":"10/02/2023",
      "status":"Issued",
      "qty":20,
      "iqty":0,
      "Items":"materail1,materail13,materail3","availqty":"54",
   
    },
    {
      "id": 5,
      "productName": "Kalyan",
      "uom": "Sq-meter",
      "dims": "Production",
      "internalPartNo": "mat5",
      "description": "Description For Request",
      "shotWeight":"Testing",
      "date":"10/02/2023",
      "status":"Issued",
      "qty":15,
      "iqty":0,
      "Items":"materail1,materail13,materail3","availqty":"54",
   
    }
  ]