export const data = [
  { "id":1,
    "productName": "R1234567",
    "uom": "Kg",
    "dims": "(10,45,16)",
    "internalPartNo": "INPN123",
    "description": "Hollow and Nailed",
    "shotWeight":"134",
  },
  {
    "id": 2,
    "productName": "RQ234567",
    "uom": "Liter",
    "dims": "(10,45,16)",
    "internalPartNo": "EPN123",
    "description": "Hollow and Nailed",
    "shotWeight":"122",
  },
  {
    "id": 3,
    "productName": "R34567QE",
    "uom": "Meter",
    "dims": "(10,45,16)",
    "internalPartNo": "RTH123",
    "description": "Hollow and Nailed",
    "shotWeight":"100",
  },
  {
    "id": 4,
    "productName": "F34567QE",
    "uom": "Qty",
    "dims": "(10,45,16)",
    "internalPartNo": "ERT123",
    "description": "Hollow and Nailed",
    "shotWeight":"96",
  },
  {
    "id": 5,
    "productName": "DF34567QE",
    "uom": "Sq-meter",
    "dims": "(10,45,16)",
    "internalPartNo": "DFTR123",
    "description": "Hollow and Nailed",
    "shotWeight":"59",
  }
]