export const data = [
  { "id":1,
    "productName": "Material1",
    "uom": "Kg",
    "date":"10/02/2023",
    "dims": "Stores",
    "internalPartNo": "INPN123",
    "description": "Description For Request",
    "shotWeight":"Hardware",
    "status":"Accepted",
    "Items":"mat1,mat2,mat3,mat4",
    "Qty":"4143",
    "RQty":"400",
    "poPartNo": "PoNo123",
    "invoice":"inNo2323",
    "inValue":"43543",
    "vecNo":"TN32RT3423",
    "supName":"Vinayaga Ventures",
    "expiryDate":"19/02/2023",
  },
  {
    "id": 2,
    "productName": "Material2",
    "uom": "Liter",
    "dims": "Quality",
    "internalPartNo": "EPN123",
    "description": "Description For Request",
    "shotWeight":"Developement",
    "date":"10/02/2023",
    "status":"Accepted",
    "Items":"materail1,materail13,materail3",
    "Qty":"14343",
    "RQty":"11",
    "poPartNo": "PoNo134",
    "invoice":"inNo453",
    "inValue":"4353",
    "vecNo":"TN32RT3856",
    "supName":"Pillaiyar Ventures",
    "expiryDate":"19/02/2023",
 
  },
  {
    "id": 3,
    "productName": "Material3",
    "uom": "Meter",
    "dims": "Production",
    "internalPartNo": "RTH123",
    "description": "Description For Request",
    "shotWeight":"Testing",
    "date":"10/02/2023",
    "status":"Accepted",
    "Items":"materail1,materail13,materail3",
    "Qty":"234",
    "RQty":"21",
    "poPartNo": "PoNo13",
    "invoice":"inNo23",
    "inValue":"3543",
    "vecNo":"TN02RT6423",
    "supName":"Ventures Stationaries",
    "expiryDate":"19/02/2023",
 
  },
  {
    "id": 4,
    "productName": "Material4",
    "uom": "Qty",
    "dims": "Administration",
    "internalPartNo": "ERT123",
    "description": "Description For Request",
    "shotWeight":"Hardware",
    "date":"10/02/2023",
    "status":"Accepted",
    "Items":"materail1,materail13,materail3",
    "Qty":"342",
    "RQty":"31",
    "poPartNo": "PoNo23",
    "invoice":"inNo3435",
    "inValue":"67865",
    "vecNo":"TN08RT3423",
    "supName":"Ynot Ventures",
    "expiryDate":"19/02/2023",
 
  },
  {
    "id": 5,
    "productName": "Material5",
    "uom": "Sq-meter",
    "dims": "Production",
    "internalPartNo": "DFTR123",
    "description": "Description For Request",
    "shotWeight":"Testing",
    "date":"10/02/2023",
    "status":"Accepted",
    "Items":"materail1,materail13,materail3",
    "Qty":"4543",
    "RQty":"89",
    "poPartNo": "PoNo123",
    "invoice":"inNo2323",
    "inValue":"43543",
    "vecNo":"TN32RT3423",
    "supName":"Vinayaga Ventures",
    "expiryDate":"19/02/2023",
 
  }
]