export const data = [
    { "id":1,
      "productName": "R1234567",
      "cusName": "ISRO",
      "part": "Nozzle",
      "quantity": "98",
      "cost": "43567",
      "status":"Awaiting Approval",
      "planDate":"10.03.2023",
      "process":"Melting",
      "shift":"1",
      "availQty":"67",
      "prodQty":"0",
      "remarks":"Need to be completed for next day plan",
      "entry":"9-03-2023",
    },
    {
      "id": 2,
      "productName": "RQ234567",
      "cusName": "BHEL",
      "part": "Compressor",
      "quantity" :"121",
      "cost": "56789",
      "status":"Approved",
      "planDate":"10.03.2023",
      "process":"Heat Treatment",
      "shift":"1",
      "availQty":"43",
      "prodQty":"0",
      "remarks":"Not Available",
      "entry":"9-03-2023",
    },
    {
      "id": 3,
      "productName": "R34567QE",
      "cusName": "BHEL",
      "part": "Exhaust",
      "quantity": "486",
      "cost": "45678",
      "status":"In-Production",
      "planDate":"10.03.2023",
      "process":"Machining",
      "shift":"1",
      "availQty":"243",
      "prodQty":"0",
      "remarks":"Take stock from inspection",
      "entry":"9-03-2023",
    },
    {
      "id": 4,
      "productName": "F34567QE",
      "cusName": "BHEL",
      "part": "Turbine",
      "quantity": "88",
      "cost": "88898",
      "status":"Partially-Dispatched",
      "planDate":"10.03.2023",
      "process":"Shot Blasting",
      "shift":"1",
      "availQty":"23",
      "prodQty":"0",
      "remarks":"Not Available",
      "entry":"9-03-2023",
    },
    {
      "id": 5,
      "productName": "DF34567QE",
      "cusName": "DRDO",
      "part": "Rotor",
      "quantity": "12",
      "cost": "12345",
      "status":"Closed",
      "planDate":"10.03.2023",
      "process":"Cuttling And Fettling",
      "shift":"2",
      "availQty":"37",
      "prodQty":"0",
      "remarks":"Compleated",
      "entry":"9-03-2023",
    }
  ]